# Generated by Django 4.2.17 on 2026-04-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='pergunta')),
                ('answer', models.TextField(verbose_name='resposta')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 = baixa, 5 = alta', verbose_name='prioridade')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='acertos')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='erros')),
                ('last_studied_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo estudo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='cards.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'flashcard',
                'verbose_name_plural': 'flashcards',
                'ordering': ['category__name', 'question'],
            },
        ),
        migrations.CreateModel(
            name='StudyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_answer', models.TextField(verbose_name='resposta digitada')),
                ('result', models.CharField(choices=[('pending', 'pendente'), ('correct', 'acertei'), ('wrong', 'errei')], default='pending', max_length=10, verbose_name='resultado')),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo de resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='respondido em')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cards.flashcard', verbose_name='flashcard')),
            ],
            options={
                'verbose_name': 'tentativa',
                'verbose_name_plural': 'tentativas',
                'ordering': ['-created_at'],
            },
        ),
    ]
